version: '3.6'
services:
  postgres-typeorm:
    image: postgres:latest
    restart: always
    volumes:
      - db_data_typeorm:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_TYPEORM}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT_TYPEORM}:5432"

  postgres-mikroorm:
    image: postgres:latest
    restart: always
    volumes:
      - db_data_mikroorm:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_MIKROORM}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT_MIKROORM}:5432"

  graphql-engine-typeorm:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres-typeorm"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres-typeorm:5432/${DB_NAME_TYPEORM}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  graphql-engine-mikroorm:
    image: hasura/graphql-engine:latest
    ports:
      - "8081:8080"
    depends_on:
      - "postgres-mikroorm"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres-mikroorm:5432/${DB_NAME_MIKROORM}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

volumes:
  db_data_typeorm:
  db_data_mikroorm: